### ISSUE TITLE
Es ist nicht möglich einem Spiel zu joinen

### ISSUE THREAD

**Issue by Mugen1991** [haw-vs-2015/rest-monopoly#1]
Ich habe versucht über  <serveradresse>/games/1/players/herbert?name=Herbert&uri=testurl einem Spiel beizutreten. Dies ist leider nicht möglich. Es wird anscheinend kein neuer Spieler erstellt.

**Comment by AlexHolly** [comment]
Starte die jar mit "java -jar vsp_abh928.jar" und schau ob  "player joinGame" ausgegeben wird. Ich probier das ganze auch nochmal.

"created game" sollte auch ausgegeben werden.

Ok du hast recht ich hab die playerid vor dem ? nicht drin

Sollte jetzt laufen.
